[package]
name = 'beos_scraping'
version = '0.1.0'
authors = ['lgarcin <laurent.garcin@gmail.com>']
edition = '2018'

[dependencies]
regex = '1.5.4'
select = '0.5.0'
clipboard = '0.5.0'
alerts = '0.1.1'

[dependencies.reqwest]
version = '0.11.4'
features = ['blocking']
