[package]
name = 'beos_scraping'
version = '0.3.0'
authors = ['lgarcin <laurent.garcin@gmail.com>']
edition = '2021'

[dependencies]
regex = '1.10.4'
select = '0.6.0'
clipboard = '0.5.0'
alerts = '0.1.1'
ureq = '2.9.7'
